### ISSUE TITLE
Package look good; add a vignette and a test

### ISSUE THREAD

**Issue by kbroman** [jeremyash/jdash#2]
The package is looking good. Please add:
- a vignette; see http://kbroman.org/pkg_primer/pages/vignettes.html
- a test or two; see http://kbroman.org/pkg_primer/pages/tests.html

**Comment by jeremyash** [comment]
I updated the package with both a vignette and tests.  It all seems to be working.  Thanks for taking a look at it while it was still in progress.

**Comment by kbroman** [comment]
Looks good! I made [some small changes](https://github.com/jeremyash/jdash/pull/3) regarding the tests.
